#weibo.py comes from http://weibo.lxyu.net/

import weibo
import webbrowser
import time
APP_KEY=''#your key
API_SECRET=''#your secret
URL='http://www.cworld.info'#your website or any website

token={}#result generated by weibo_1st.py

c2 = weibo.Client(APP_KEY, API_SECRET, URL, token)
l=c2.get('statuses/user_timeline', uid=2680925293)
print(l)
url='http://www.cworld.info'
mystr='当前时间: '
c_time=time.mktime(time.localtime())
c_time-=(11*60*60)#US west time to Beijing Time
a=time.strftime("%Y年%m月%d日  %H:%M:%S", time.localtime(c_time))
mystr=mystr+a+url
c2.post('statuses/share',status=mystr)
